Models/Admin/AdmissionForm/AdmissionForm.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using DatabaseTVP;
using FYP1.Models.Institute;
namespace FYP1.Models.Admin.AdmissionForm
{
    public class AdmissionForm
    {
        public int Query { get; set; }
        public int Admission_id { get; set; }
        public int S_ID { get; set; }
        public int Degree_ID { get; set; }

        public List<Admission_Institute> Inst_List { get; set; }
        public int Admission_Add()
        {   
            SqlCommand sc = new SqlCommand("Usp_InsertUpdateDelete_AdmissionForm", Connection.Get()) { CommandType = System.Data.CommandType.StoredProcedure }; ;
            sc.Parameters.AddWithValue("@S_ID", S_ID); // seshan se uth k aarai hai or view mei hide karwadi
            sc.Parameters.AddWithValue("@Degree_ID", Degree_ID);
            sc.Parameters.AddWithValue("@Query", 1);
            object id = sc.ExecuteScalar();
            return Convert.ToInt32((decimal)id);
        }
    }
    public class Admission_Institute
    {
        public int AI_ID { get; set; }
        public int I_ID { get; set; }
        public int A_ID { get; set; }
        public int Status_ID { get; set; }
        public string Payment_Info { get; set; }
        public string Message { get; set; }
        public void Add()
        {
            SqlCommand sc = new SqlCommand("Usp_InsertUpdateDelete_AdmissionInstitute", Connection.Get()) { CommandType = System.Data.CommandType.StoredProcedure }; ;
            sc.Parameters.AddWithValue("@A_ID", A_ID); 
            sc.Parameters.AddWithValue("@I_ID", I_ID);
            sc.Parameters.AddWithValue("@Query", 1);
            object id = sc.ExecuteScalar();
         }
      public string Pay()
        {
            SqlCommand sc = new SqlCommand("Usp_InsertUpdateDelete_AdmissionInstitute", Connection.Get()) { CommandType = System.Data.CommandType.StoredProcedure }; ;
            sc.Parameters.AddWithValue("@AI_ID", AI_ID);
            sc.Parameters.AddWithValue("@Status", 2);
            sc.Parameters.AddWithValue("@Query", 2);
            SqlDataReader sdr =sc.ExecuteReader();
            while (sdr.Read())
            {
                Payment_Info=(string)sdr[0];
            }
            sdr.Close();
            return Payment_Info;
        }
        public void Response()
        {
            SqlCommand sc = new SqlCommand("Usp_InsertUpdateDelete_AdmissionInstitute", Connection.Get()) { CommandType = System.Data.CommandType.StoredProcedure }; ;
            sc.Parameters.AddWithValue("@AI_ID", AI_ID);
            sc.Parameters.AddWithValue("@Status", Status_ID);
            sc.Parameters.AddWithValue("@Query",2);
            sc.ExecuteNonQuery();
        }

        public string Total_Admissions_Stats()
        {
            try
            {
                string Message = DataBase.ExecuteQuery<Admission_Institute>(new {  }, Connection.Get()).FirstOrDefault().Message;
                return Message;
            }
            catch (Exception ex)
            {
                return null;
            }
        }
    }



}

Controllers/AdmissionFormController.cs
using FYP1.Models;
using FYP1.Models.Admin;
using FYP1.Models.Admin.AdmissionForm;
using FYP1.Models.Department;
using FYP1.Models.Institute;
using FYP1.Models.Student;
using FYP1.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Web.Mvc;

namespace FYP1.Controllers
{
    public class AdmissionFormController : Controller
    {



        // GET: AdmissionForm

        [Student_Session]
        [HttpGet]
        public ActionResult Add()
        {
            //University u = new University();
            //u.GetData();

            #region Fuzzy Logic

            //u.UB_ActAvg = u.getUpperBound(u.ActAvg);
            //u.FV_ActAvg = u.getFuzzyValues(u.ActAvg, u.UB_ActAvg, true);

            //u.UB_SatAvg = u.getUpperBound(u.SatAvg);
            //u.FV_SatAvg = u.getFuzzyValues(u.SatAvg, u.UB_SatAvg, true);

            //u.UB_AcceptanceRate = u.getUpperBound(u.AcceptanceRate);
            //u.FV_AcceptanceRate = u.getFuzzyValues(u.AcceptanceRate, u.UB_AcceptanceRate, false);

            //u.UB_PercentReceivingAid = u.getUpperBound(u.PercentReceivingAid);
            //u.FV_PercentReceivingAid = u.getFuzzyValues(u.PercentReceivingAid, u.UB_PercentReceivingAid, false);

            //u.UB_CostAfterAid = u.getUpperBound(u.CostAfterAid);
            //u.FV_CostAfterAid = u.getFuzzyValues(u.CostAfterAid, u.UB_CostAfterAid, true);

            //u.UB_TuitionFee = u.getUpperBound(u.TuitionFee);
            //u.FV_TuitionFee = u.getFuzzyValues(u.TuitionFee, u.UB_TuitionFee, true);

            //u.UB_Rank = u.getUpperBound(u.Rank);
            //u.FV_Rank = u.getFuzzyValues(u.Rank, u.UB_Rank, false);

            //u.UB_Control = u.getUpperBound(u.Control);
            //u.FV_Control = u.getFuzzyValues(u.Control, u.UB_Control, false);

            //u.FuzzyLogic();
            //List<University_View> lst = u.Sort();
            //ViewBag.uni = lst;

            #endregion

            //ViewBag.cities = new University().GetCities();
            ViewBag.DegreeLevel = new DegreeLevel().DegreeLevel_Get_All();
            ViewBag.Department = new Department().DepartmentAndType_Get_All();
            ViewBag.Degree = new Degree().Degree_Get_All();
            ViewBag.Payment_Info = new Admin().Admin_Get().Payment_Info;

            var lst = new AdmissionViewModel() { S_ID = (int)Session["S_ID"] }.Get_Student_Admission();
            //int ids = new AdmissionForm();
            List<int> ids = new List<int>();
            foreach (var item in lst)
            {
                ids.Add(item.Institute_ID);
            }
            ViewBag.ids = ids;
             ViewBag.insdetail = new Chat() { S_ID = (int)Session["S_ID"] }.institutebyid();
            if (Session["S_ID"] != null)
            {
                int id = (int)Session["S_ID"];
                AdmissionForm s = new AdmissionForm() { S_ID = id };
                return View(s);
            }
           
            return View();
        }[HttpGet]
        public ActionResult index()
        {
            
           
            return View();
        }
        [HttpPost]
        public ActionResult Add(AdmissionForm obj)
        {
            obj.Inst_List = obj.Inst_List.FindAll(x => x.I_ID != 0);
            //AdminViewModel a = new AdminViewModel();
            //List<Institute> lis = a.institute.Institute_Get_All().ToList();
            //ViewBag.InstituteList = new SelectList(lis, "Institute_ID", "Institute_Name");
            //a.institute.Institute_ID = a.institute.Institute_ID;
            int A_ID = obj.Admission_Add();

            foreach (var item in obj.Inst_List)
            {
                item.A_ID = A_ID; // last admission ID
                item.Add();
            }
            return RedirectToAction("AdmissionStatus");
        }
        public ActionResult GetByDeprtment(int D_ID)
        {
            return Json(new Institute().Institute_Get_By_Deprt(D_ID), JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetByDegree(int Degree_ID)
        {
            var listOfuni = new Institute().Institute_Get_By_Degree(Degree_ID);
          
            return Json(listOfuni, JsonRequestBehavior.AllowGet);
        }
        //public ActionResult GetUni(University_View model)
        //{
        //    University u = new University();
        //    u.GetData();

        //    #region Fuzzy Logic

        //    u.UB_ActAvg = u.getUpperBound(u.ActAvg);
        //    u.FV_ActAvg = u.getFuzzyValues(u.ActAvg, u.UB_ActAvg, false);

        //    u.UB_SatAvg = u.getUpperBound(u.SatAvg);
        //    u.FV_SatAvg = u.getFuzzyValues(u.SatAvg, u.UB_SatAvg, false);

        //    u.UB_AcceptanceRate = u.getUpperBound(u.AcceptanceRate);
        //    u.FV_AcceptanceRate = u.getFuzzyValues(u.AcceptanceRate, u.UB_AcceptanceRate, false);

        //    u.UB_PercentReceivingAid = u.getUpperBound(u.PercentReceivingAid);
        //    u.FV_PercentReceivingAid = u.getFuzzyValues(u.PercentReceivingAid, u.UB_PercentReceivingAid, false);

        //    u.UB_CostAfterAid = u.getUpperBound(u.CostAfterAid);
        //    u.FV_CostAfterAid = u.getFuzzyValues(u.CostAfterAid, u.UB_CostAfterAid, false);

        //    u.UB_TuitionFee = u.getUpperBound(u.TuitionFee);
        //    u.FV_TuitionFee = u.getFuzzyValues(u.TuitionFee, u.UB_TuitionFee, false);

        //    u.UB_Rank = u.getUpperBound(u.Rank);
        //    u.FV_Rank = u.getFuzzyValues(u.Rank, u.UB_Rank, false);

        //    u.UB_Control = u.getUpperBound(u.Control);
        //    u.FV_Control = u.getFuzzyValues(u.Control, u.UB_Control, false);

        //    u.FuzzyLogic();
        //    List<University_View> lst = u.Sort();


        //    #endregion

        //    lst = lst.FindAll(x =>x.P_City==model.P_City );
        //    lst = lst.FindAll(x =>x.P_TuitionFee <= model.P_TuitionFee);
        //    lst = lst.FindAll(x =>x.P_Rank >= model.P_Rank);
        //    return Json(lst, JsonRequestBehavior.AllowGet);
        //}
        public ActionResult GetDegreeByDeprtment(int D_ID)
        {
            return Json(new Degree().Degree_Get_By_Deprtment(D_ID), JsonRequestBehavior.AllowGet);
        }
     

        [Admin_Session]
        //Admin
        public ActionResult Get_Unpaid_Admission()
        {
            ViewBag.Payment_Info = Session["Payment_Info"];
            return View(new AdmissionViewModel().Get_Admission_For_Admin());
        }



        [HttpGet]
        public ActionResult GetQuizQuestion()
        {
            // Quiz qs = new Quiz();

            //object q= new Quiz().get().ToList();


            // qs.choicess = new Quiz.quiz_choice().Getchoices().Where(a=>a.quiz_ques_id==q.quiz_question_id).Select(a=>new Quiz.quiz_choice{choices=a.choices }).ToList();
            Quiz_user_score qu = new Quiz_user_score();
            qu.student_id= (int)Session["S_ID"];
            ViewBag.data = qu.getbyid().student_id;


            return View(new Quiz().get().ToList());
        }
        [HttpPost]
        public ActionResult GetQuizQuestion(List<Quiz_user_answer>  quiz)
        {
            
            List<quiz_choice> qc = new quiz_choice().Getchoices();
            int id = (int)Session["S_ID"];
            int count = 0;
            List<Quiz_user_answer> finalresult = new List<Quiz_user_answer>();
            foreach (Quiz_user_answer ans in quiz)
            {
                if (ans.answer != null)
                {
                    Quiz_user_answer qa = new Quiz_user_answer();
                    qa.student_id = id;
                    qa.quiz_choice_id = ans.quiz_choice_id;
                    qa.quiz_ques_id = ans.quiz_ques_id;
                    qa.answer = ans.answer.ToLower();
                    qa.count = count;

                    foreach (var item in qc)
                    {
                        if (ans.quiz_ques_id == item.quiz_ques_id && ans.answer == item.choices && item.is_correct_choice == true)
                        {
                            qa.Is_correct = true;
                            count++;
                            break;
                        }
                        else
                        {
                            qa.Is_correct = false;
                            if (ans.quiz_ques_id==item.quiz_ques_id && ans.answer != item.choices && item.is_correct_choice==true)
                            {
                                qa.answer = item.choices;
                            }
                            
                        }
                    }

                    finalresult.Add(qa);
                    qa.Add();
                }


            }
            if (finalresult.Count > 0)
            {


                Quiz_user_score qus = new Quiz_user_score();
                qus.student_id = id;
                qus.score = count;
                qus.Add();
                return Json(new { qa = finalresult }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, responseText = "The attached file is not supported." }, JsonRequestBehavior.AllowGet);
            }
        }







        [Admin_Session]
        [HttpGet]
        public ActionResult PayAdmission(int AI_ID)
        {
           Session["Payment_Info"]= new Admission_Institute() { AI_ID = AI_ID }.Pay();
            return RedirectToAction("Get_Unpaid_Admission");
        }

        //[Institute_Session,Admin_Session]
        
public ActionResult Get_All_Admission()
        {
            return View(new AdmissionViewModel().Get_All_Admission_For_Admin()) ;
        }
        public ActionResult Get_Paid_Admission()
        {
            ViewBag.stddetail = new Chat() { Institute_ID = (int)Session["I_ID"] }.studentbyid();
            return View(new AdmissionViewModel().Get_Admission_For_Institute((int)Session["I_ID"]));
        }
        public ActionResult StudentSearch(int S_ID)
        {

Views/AdmissionForm/AdmissionStatus.cshtml
@model IEnumerable<FYP1.Models.Admin.AdmissionForm.AdmissionViewModel>

@{
    ViewBag.Title = "Get_Unpaid_Admission";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";

}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header" data-background-color="purple">
                        <h4 class="title"><b>Application Status</b></h4>
                        <p class="category">
                           
                                @Html.ActionLink("New Application", "Add", "AdmissionForm")
                            <br />

                        </p>
                    </div>
                    <div class="card-content">
                        <table class="table  table-hover">
                            <tr>

                                <th>
                                    @Html.DisplayNameFor(model => model.Student_Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CNIC_No)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Father_Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Institute_Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Degree_Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Status)


                                </th>
                                <th></th>
                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Student_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CNIC_No)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Father_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Institute_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Degree_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Status)


                                    </td>

                                </tr>
                            }

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/AdmissionForm/GetQuizQuestion.cshtml
@model IEnumerable<FYP1.Models.Quiz>

@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
@*<div class="block">
        @Html.DisplayNameFor(model => model.question)
    </div>
    @{
        int count = 1;
    }
    @foreach (var item in Model)
    {
        <div class="block">
            <span>@count  :</span>      @Html.DisplayFor(modelItem => item.question)
        </div>
        foreach (var items in item.choicess)
        {
            <div class="choices">
                       <input type="radio" name="@items.choices" class="radio-inline" />@Html.DisplayFor(m=>items.choices)
                </div>

        }

        count++;
    }*@

@{ int count = 1, countR = 0; }
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-11">
                <div class="card">
                    <div class="card-header" data-background-color="purple">
                        <h4 class="title"><b>Quiz</b></h4>
                        <p class="category"><b></b></p>
                    </div>
                    <div class="card-content">
                        <div class="Quiz">
                            @if (Model != null && Model.Any())
                            {
                                var stuid = ViewBag.data;
                                foreach (var item in Model)
                                {
                                    <div class="BlockQ" style="border: 1px solid #bdbdbd; width: 75%; border-radius: 20px; margin-top: 40px;margin-left:5%;margin-right:5%; background-color: #f0ffff; padding: 8px;">
                                        <div class="Question" style="padding: 2%;">
                                            <span class="label label-warning"> @string.Format("{0}{1}.", "Q", count)</span>
                                            <span id="@string.Format("{0}{1}", "ID_Q", count)" style="display:none;">@item.quiz_question_id</span>
                                            <p style="display: inline; padding: 3%;" id="@string.Format("{0}{1}", "Q", count)">@item.question</p>
                                        </div>

                                        <div class="Choices" style="margin-left: 8%;margin-bottom:3%;">
                                            @foreach (var items in item.choicess)
                                            {
                                                <label class="radio-inline">
                                                    <span id="@string.Format("{0}{1}", "ID_C", count)" style="display:none;">@items.quiz_choice_id</span>

                                                    <input type="radio" name="@string.Format("{0}{1}", "inlineRadioOptions", count)" id="@string.Format("{0}{1}", "inlineRadio", countR)" value="@items.choices" style="margin-left: -16px;"> @items.choices

                                                </label><br />
                                                countR++;
                                            }
                                        </div> <!--END Choices-->

                                        <div id="@string.Format("{0}{1}{2}", "Ans", "Q", count)">


                                        </div>
                                    </div> <!-- END BlockQ -->
                                    count++;
                                }
                                <span id="countQuections" style="display:none;">@count</span>

                                <button type="button" id="SubmitQuiz" class="btn btn-primary" style="margin-top: 10px;"> Submit Quiz </button>

                            }
                        </div> <!-- END QUIZ -->

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts
{
    <script>


        $(document).ready(function () {

            $('#SubmitQuiz').on('click', function () {

                //count Questions
                var sel = $('#countQuections').text();

                console.log(sel);

                var resultQuiz = [], countQuestion = parseInt(sel), question = {}, j = 1;

                for (var i = 1; i < countQuestion; i++) {
                    question = {
                        quiz_ques_id: $('#ID_Q'+ i).text(),
                        quiz_choice_id: $('#ID_C' + i).text()
                        ,answer: $('input[name=inlineRadioOptions' + i + ']:checked').val()
                    }

                    resultQuiz.push(question);
                }
                debugger;

                resultQuiz = JSON.stringify({ 'quiz': resultQuiz});

                $.ajax({
                    contentType: 'application/json; charset=utf-8',
                    dataType: 'json',
                    type: 'POST',
                    url: '@Url.Action("GetQuizQuestion", "AdmissionForm")',
                    data: resultQuiz,
                    success: function (response) {
                        if (response.qa.length > 0) {
                            var j = 1;
                            count = 0;
                            for (var i = 0; i < response.qa.length; i++) {
                                if (response.qa[i].Is_correct == true) {
                                    debugger;
                                    $('#AnsQ' + j).html('<div class="alert alert-success" role="alert"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Correct answer</div>');
                                    count++;
                                }

                                else {
                                    $('#AnsQ' + j).html('<div class="alert alert-danger" role="alert"> <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span> Incorrect answer - The Good Answer is <b>' + response.qa[i].answer + '</b></div>');
                                }
                                j++;
                            }
                            debugger;
                            swal("Congratulation!", "You marks is " + count, "success");
                        }
                        else {
                            alert("Something Wrong");
                        }
                    },

                    failure: function (response) {
                        alert(response);
                    }
                });
                console.log(resultQuiz);

            });



        });


        $(document).ready(function ()
        {

        $('#SubmitQuiz').click(function () {

            if ($("#SubmitQuiz").prop('disabled')) $("SubmitQuiz").prop('disabled', false);
        else $("#SubmitQuiz").prop('disabled', true);
        });
        })
    </script>



}

Views/AdmissionForm/Get_All_Admission.cshtml
@model IEnumerable<FYP1.Models.Admin.AdmissionForm.AdmissionViewModel>

@{
    ViewBag.Title = "All Admission";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}




<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="purple">
                <h2>All Admission</h2>
                <p class="category">@Html.ActionLink("Create New", "Create")</p>
            </div>
            <div class="card-content table-responsive">
                <table class="table">
                    <thead class="text-gray">
                    <th>
                        @Html.DisplayNameFor(model => model.Student_Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CNIC_No)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Father_Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Institute_Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Degree_Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>
                        Mark
                    </th>
                    <th></th>


                    </thead>



                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Student_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CNIC_No)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Father_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Institute_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Degree_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Status)
                                </td>
                                <td>
                                    <button onclick="window.location.href='@Url.Action("StudentSearch","AdmissionForm",new { S_ID=item.S_ID})'" value="Pay">
                                        Details
                                    </button>
                                </td>
                                <td>
                                    <button onclick="window.location.href='@Url.Action("AdmissionResponse","AdmissionForm",new { AI_ID=item.AI_ID,Status_ID=3})'" value="Pay">
                                        Accept
                                    </button>
                                    <button onclick="window.location.href='@Url.Action("AdmissionResponse","AdmissionForm",new { AI_ID=item.AI_ID,Status_ID=4})'" value="Pay">
                                        Reject
                                    </button>
                                </td>

                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script>
        (function (t, a, l, k, j, s) {
            s = a.createElement('script'); s.async = 1; s.src = "https://cdn.talkjs.com/talk.js"; a.head.appendChild(s)
            ; k = t.Promise; t.Talk = {
                v: 3, ready: {
                    then: function (f) {
                        if (k) return new k(function (r, e) { l.push([f, r, e]) }); l
                            .push([f])
                    }, catch: function () { return k && new k() }, c: l
                }
            };
        })(window, document, []);
    </script>






    <script>

        function openForm() {
            debugger;
            document.getElementById("myForm").style.display = "block";
            var ls = @Html.Raw(Json.Encode(ViewBag.stddetail));
            var btn = $('#ab');
            var b = ""



            $.each(ls, function (k, ktem) {
                debugger;
                b = ""
                b += " <h1  class='btn'   id = " + ktem.S_ID + " onclick = 'opendiv(this.id)' > " + ktem.Student_Name + " </h1 > "
                btn.append(b);

            });

        }


        function closeForm() {
            document.getElementById("myForm").style.display = "none";


        }

        function opendiv(value) {

            var bs = @Html.Raw(Json.Encode(ViewBag.stddetail));
            $.each(bs, function (l, ltem) {
                if (ltem.S_ID == value) {
                    debugger;
                    Talk.ready.then(function() {
                        var me = new Talk.User({
                            id: String(ltem.Institute_ID),
                            name: ltem.Institute_Name,
                            email: "alice@example.com",
                            photoUrl: "https://demo.talkjs.com/img/alice.jpg",
                            welcomeMessage: "Hey there! How are you? :-)"
                        });
                        window.talkSession = new Talk.Session({
                            appId: "tX8hryM7",
                            me: me
                        });
                        var other = new Talk.User({
                            id: String(ltem.S_ID),
                            name: ltem.Student_Name,
                            email: "Sebastian@example.com",
                            photoUrl: "https://demo.talkjs.com/img/sebastian.jpg",
                            welcomeMessage: "Hey, how can I help?"
                        });

                        var conversation = talkSession.getOrCreateConversation(Talk.oneOnOneId(me, other))
                        conversation.setParticipant(me);
                        conversation.setParticipant(other);
                        var inbox = talkSession.createInbox({selected: conversation});
                        inbox.mount(document.getElementById("talkjs-container"));
                    });
                    debugger;
                }
            });


            debugger;
        }





    </script>










}

<style>
    .open-button {
        background-color: #555;
        color: white;
        padding: 16px 20px;
        border: none;
        cursor: pointer;
        opacity: 0.8;
        position: fixed;
        bottom: 23px;
        right: 28px;
        width: 280px;
    }

    /* The popup chat - hidden by default */
    .chat-popup {
        display: none;
        position: fixed;
        bottom: 0;
        right: 15px;
        margin: auto;
        border: 3px solid #f1f1f1;
        z-index: 9;
    }

    /* Add styles to the form container */
    .form-container {
        max-width: 300px;
        padding: 10px;
        background-color: white;
    }



        /* Set a style for the submit/send button */
        .form-container .btn {
            background-color: #4CAF50;
            color: white;
            padding: 16px 20px;
            border: none;
            cursor: pointer;
            width: 100%;
            margin-bottom: 10px;
            opacity: 0.8;
        }

        /* Add a red background color to the cancel button */
        .form-container .cancel {
            background-color: red;
        }

        /* Add some hover effects to buttons */
        .form-container .btn:hover, .open-button:hover {
            opacity: 1;
        }
</style>